### ISSUE TITLE
Reading special registers and relays

### ISSUE THREAD

**Issue by deepcoder** [kj831ca/FX3U_ESP32_Part1#1]
First, a big thank you for your two videos and code. Very helpful and well done.

This is really not a bug in your code in anyway.

I was thinking about extending your example code and wanted to check to see if the PLC was running and if had been reset. So I tried to read the relay M8000 for run state and the registers that hold the date and time. However, I am not able to read these 'special' locations, I was wondering if you had any success reading these. When I try to do a Modbus read of these registers and relays I do not get valid values. May well be a stupid mistake on my part or perhaps a different manufacture of the device that I have...

Anyway, thanks again and if you have any insight on reading these locations.

**Comment by kj831ca** [comment]
In the LE3U manual stated that you can read/write M register (0-1023) and for D Register (0-4095)  on page 15
https://www.xueplc.com/wp-content/uploads/2021/01/LE3u-analog-485.pdf 

So I don't think you can directly read those special M8XXX registers or D8XXX because it is beyond address limit of ModBus RTU PLC spec. In order to read those register for example reading hour register D8015, you can add  PLC ladder to copy D8015 =>D0001 and read from D0001.

**Comment by deepcoder** [comment]
Thanks very much for reply and your good eyes on the topic!

Your interpretation of the manual helps to give me a better view on how to understand the operational capabilities of these devices.

I made a number of 'ass'umptions ;-) that I should not have. for example assuming that the modbus interface would be operating when the run switch was off. It does appear to do so, however as you point not with only a subset of the total registers and relays exposed.

As you point out, I think I can get the date and time out, however the run/stop state is another story. That relay sure seems like a useful one to expose via modbus, along with error state... oh well on a price adjusted basis, still a useful device so far.
